package wallapp.country

import wallapp.currency.Currency
import wallapp.language.Iso

enum class Country(
    val label: String,
    val billingCurrency: Currency,
    val isoAlpha2: Iso,
    val isoAlpha3: Iso,
    val isTier1: Boolean = false,
) {
    Afghanistan("Afghanistan", Currency.UnitedStatesDollar, "af", "afg"),
    Albania("Albania", Currency.UnitedStatesDollar, "al", "alb"),
    Algeria("Algeria", Currency.AlgerianDinar,"dz", "dza"),
    Angola("Angola", Currency.UnitedStatesDollar, "ao", "ago"),
    Anguilla("Anguilla", Currency.UnitedStatesDollar, "ai", "aia"),
    AntiguaAndBarbuda("AntiguaAndBarbuda", Currency.UnitedStatesDollar, "ag", "atg"),
    Argentina("Argentina", Currency.UnitedStatesDollar, "ar", "arg"),
    Armenia("Armenia", Currency.UnitedStatesDollar, "am", "arm"),
    Australia("Australia", Currency.AustralianDollar, "au", "aus", isTier1 = true),
    Austria("Austria", Currency.Euro, "at", "aut", isTier1 = true),
    Azerbaijan("Azerbaijan", Currency.UnitedStatesDollar, "az", "aze"),
    Bahamas("Bahamas", Currency.UnitedStatesDollar, "bs", "bhs"),
    Bahrain("Bahrain", Currency.UnitedStatesDollar, "bh", "bhr"),
    Bangladesh("Bangladesh", Currency.BangladeshiTaka, "bd", "bgd"),
    Barbados("Barbados", Currency.UnitedStatesDollar, "bb", "brb"),
    Belarus("Belarus", Currency.UnitedStatesDollar, "by", "blr"),
    Belgium("Belgium", Currency.Euro, "be", "bel", isTier1 = true),
    Belize("Belize", Currency.UnitedStatesDollar, "bz", "blz"),
    Benin("Benin", Currency.UnitedStatesDollar, "bj", "ben"),
    Bermuda("Bermuda", Currency.UnitedStatesDollar, "bm", "bmu"),
    Bhutan("Bhutan", Currency.UnitedStatesDollar, "bt", "btn"),
    Bolivia("Bolivia", Currency.BolivianBoliviano, "bo", "bol"),
    Brazil("Brazil", Currency.BrazilianReal, "br", "bra"),
    BritishVirginIslands("BritishVirginIslands", Currency.UnitedStatesDollar, "vg", "vgb", isTier1 = false),
    Brunei("Brunei", Currency.UnitedStatesDollar, "bn", "brn"),
    Bulgaria("Bulgaria", Currency.BulgarianLev, "bg", "bgr"),
    BurkinaFaso("BurkinaFaso", Currency.UnitedStatesDollar, "bf", "bfa"),
    Cambodia("Cambodia", Currency.UnitedStatesDollar, "kh", "khm"),
    Cameroon("Cameroon", Currency.UnitedStatesDollar, "cm", "cmr"),
    Canada("Canada", Currency.CanadianDollar, "ca", "can", isTier1 = true),
    CapeVerde("CapeVerde", Currency.UnitedStatesDollar, "cv", "cpv"),
    CaymanIslands("CaymanIslands", Currency.UnitedStatesDollar, "ky", "cym"),
    Chad("Chad", Currency.UnitedStatesDollar, "td", "tcd"),
    Chile("Chile", Currency.ChileanPeso, "cl", "chl"),
    China("China", Currency.ChineseYuan, "cn", "chn"),
    Colombia("Colombia", Currency.ColombianPeso, "co", "col"),
    Congo("Congo", Currency.UnitedStatesDollar, "cg", "cog"),
    CostaRica("CostaRica", Currency.CostaRicanColon, "cr", "cri"),
    CoteDivoire("CoteDivoire", Currency.UnitedStatesDollar, "ci", "civ"),
    Croatia("Croatia", Currency.Euro, "hr", "hrv"),
    Cyprus("Cyprus", Currency.Euro, "cy", "cyp"),
    Czechia("Czechia", Currency.CzechKoruna, "cz", "cze"),
    Denmark("Denmark", Currency.DanishKrone, "dk", "dnk", isTier1 = true),
    Dominica("Dominica", Currency.UnitedStatesDollar, "dm", "dma"),
    DominicanRepublic("DominicanRepublic", Currency.UnitedStatesDollar, "do", "dom"),
    Ecuador("Ecuador", Currency.UnitedStatesDollar, "ec", "ecu"),
    Egypt("Egypt", Currency.EgyptianPound, "eg", "egy"),
    ElSalvador("ElSalvador", Currency.UnitedStatesDollar, "sv", "slv"),
    Estonia("Estonia", Currency.Euro, "ee", "est"),
    Eswatini("Eswatini", Currency.UnitedStatesDollar, "sz", "swz"),
    Fiji("Fiji", Currency.UnitedStatesDollar, "fj", "fji"),
    Finland("Finland", Currency.Euro, "fi", "fin", isTier1 = true),
    France("France", Currency.Euro, "fr", "fra", isTier1 = true),
    Gabon("Gabon", Currency.UnitedStatesDollar, "ga", "gab"),
    Gambia("Gambia", Currency.UnitedStatesDollar, "gm", "gmb"),
    Georgia("Georgia", Currency.GeorgianLari, "ge", "geo"),
    Germany("Germany", Currency.Euro, "de", "deu", isTier1 = true),
    Ghana("Ghana", Currency.GhanaianCedi, "gh", "gha"),
    Gibraltar("Gibraltar", Currency.BritishPound, "gi", "gib"),
    Greece("Greece", Currency.Euro, "gr", "grc"),
    Grenada("Grenada", Currency.UnitedStatesDollar, "gd", "grd"),
    Guatemala("Guatemala", Currency.UnitedStatesDollar, "gt", "gtm"),
    GuineaBissau("GuineaBissau", Currency.UnitedStatesDollar, "gw", "gnb"),
    Guyana("Guyana", Currency.UnitedStatesDollar, "gy", "guy"),
    Honduras("Honduras", Currency.UnitedStatesDollar, "hn", "hnd"),
    HongKong("HongKong", Currency.HongKongDollar, "hk", "hkg", isTier1 = true),
    Hungary("Hungary", Currency.HungarianForint, "hu", "hun"),
    Iceland("Iceland", Currency.UnitedStatesDollar, "is", "isl"),
    India("India", Currency.IndianRupee, "in", "ind"),
    Indonesia("Indonesia", Currency.IndonesianRupiah, "id", "idn"),
    Iraq("Iraq", Currency.UnitedStatesDollar, "iq", "irq"),
    Ireland("Ireland", Currency.Euro, "ie", "irl", isTier1 = true),
    Israel("Israel", Currency.IsraeliShekel, "il", "isr"),
    Italy("Italy", Currency.Euro, "it", "ita", isTier1 = true),
    Japan("Japan", Currency.JapaneseYen, "jp", "jpn", isTier1 = true),
    Jordan("Jordan", Currency.JordanianDinar, "jo", "jor"),
    Kazakhstan("Kazakhstan", Currency.KazakhstaniTenge, "kz", "kaz"),
    Kenya("Kenya", Currency.KenyanShilling, "ke", "ken"),
    Kosovo("Kosovo", Currency.UnitedStatesDollar, "xk", "xkx"),
    Kuwait("Kuwait", Currency.UnitedStatesDollar, "kw", "kwt"),
    Kyrgyzstan("Kyrgyzstan", Currency.UnitedStatesDollar, "kg", "kgz"),
    Laos("Laos", Currency.UnitedStatesDollar, "la", "lao"),
    Latvia("Latvia", Currency.Euro, "lv", "lva"),
    Lebanon("Lebanon", Currency.UnitedStatesDollar, "lb", "lbn"),
    Liberia("Liberia", Currency.UnitedStatesDollar, "lr", "lbr"),
    Libya("Libya", Currency.UnitedStatesDollar, "ly", "lby"),
    Liechtenstein("Liechtenstein", Currency.SwissFranc, "li", "lie"),
    Lithuania("Lithuania", Currency.Euro, "lt", "ltu"),
    Luxembourg("Luxembourg", Currency.Euro, "lu", "lux", isTier1 = true),
    Macao("Macao", Currency.MacanesePataca, "mo", "mac"),
    Madagascar("Madagascar", Currency.UnitedStatesDollar, "mg", "mdg"),
    Malawi("Malawi", Currency.UnitedStatesDollar, "mw", "mwi"),
    Malaysia("Malaysia", Currency.MalaysianRinggit, "my", "mys"),
    Maldives("Maldives", Currency.UnitedStatesDollar, "mv", "mdv"),
    Mali("Mali", Currency.UnitedStatesDollar, "ml", "mli"),
    Malta("Malta", Currency.Euro, "mt", "mlt"),
    Mauritania("Mauritania", Currency.UnitedStatesDollar, "mr", "mrt"),
    Mauritius("Mauritius", Currency.UnitedStatesDollar, "mu", "mus"),
    Mexico("Mexico", Currency.MexicanPeso, "mx", "mex"),
    Micronesia("Micronesia", Currency.UnitedStatesDollar, "fm", "fsm"),
    Moldova("Moldova", Currency.UnitedStatesDollar, "md", "mda"),
    Monaco("Monaco", Currency.Euro, "mc", "mco", isTier1 = true),
    Mongolia("Mongolia", Currency.UnitedStatesDollar, "mn", "mng"),
    Montenegro("Montenegro", Currency.Euro, "me", "mne"),
    Montserrat("Montserrat", Currency.UnitedStatesDollar, "ms", "msr"),
    Morocco("Morocco", Currency.MoroccanDirham, "ma", "mar"),
    Mozambique("Mozambique", Currency.UnitedStatesDollar, "mz", "moz"),
    Myanmar("Myanmar", Currency.MyanmarKyat, "mm", "mmr"),
    Namibia("Namibia", Currency.UnitedStatesDollar, "na", "nam"),
    Nauru("Nauru", Currency.UnitedStatesDollar, "nr", "nru"),
    Nepal("Nepal", Currency.UnitedStatesDollar, "np", "npl"),
    Netherlands("Netherlands", Currency.Euro, "nl", "nld", isTier1 = true),
    NewZealand("NewZealand", Currency.NewZealandDollar, "nz", "nzl", isTier1 = true),
    Nicaragua("Nicaragua", Currency.UnitedStatesDollar, "ni", "nic"),
    Niger("Niger", Currency.UnitedStatesDollar, "ne", "ner"),
    Nigeria("Nigeria", Currency.NigerianNaira, "ng", "nga"),
    NorthMacedonia("NorthMacedonia", Currency.UnitedStatesDollar, "mk", "mkd"),
    Norway("Norway", Currency.NorwegianKrone, "no", "nor", isTier1 = true),
    Oman("Oman", Currency.UnitedStatesDollar, "om", "omn"),
    Pakistan("Pakistan", Currency.PakistaniRupee, "pk", "pak"),
    Palau("Palau", Currency.UnitedStatesDollar, "pw", "plw"),
    Panama("Panama", Currency.UnitedStatesDollar, "pa", "pan"),
    PapuaNewGuinea("PapuaNewGuinea", Currency.UnitedStatesDollar, "pg", "png"),
    Paraguay("Paraguay", Currency.ParaguayanGuarani, "py", "pry"),
    Peru("Peru", Currency.PeruvianSol, "pe", "per"),
    Philippines("Philippines", Currency.PhilippinePeso, "ph", "phl"),
    Poland("Poland", Currency.PolishZloty, "pl", "pol"),
    Portugal("Portugal", Currency.Euro, "pt", "prt"),
    Qatar("Qatar", Currency.QatariRiyal, "qa", "qat"),
    Romania("Romania", Currency.RomanianLeu, "ro", "rou"),
    Russia("Russia", Currency.RussianRuble,"ru", "rus"),
    Rwanda("Rwanda", Currency.UnitedStatesDollar, "rw", "rwa"),
    SanMarino("SanMarino", Currency.Euro, "sm", "smr"),
    SaudiArabia("SaudiArabia", Currency.SaudiRiyal, "sa", "sau"),
    Senegal("Senegal", Currency.UnitedStatesDollar, "sn", "sen"),
    Serbia("Serbia", Currency.SerbianDinar, "rs", "srb"),
    Seychelles("Seychelles", Currency.UnitedStatesDollar, "sc", "syc"),
    SierraLeone("SierraLeone", Currency.UnitedStatesDollar, "sl", "sle"),
    Singapore("Singapore", Currency.SingaporeDollar, "sg", "sgp", isTier1 = true),
    Slovakia("Slovakia", Currency.Euro, "sk", "svk"),
    Slovenia("Slovenia", Currency.Euro, "si", "svn"),
    SoaTomeAndPrincipe("SoaTomeAndPrincipe", Currency.UnitedStatesDollar, "st", "stp"),
    SolomonIslands("SolomonIslands", Currency.UnitedStatesDollar, "sb", "slb"),
    SouthAfrica("SouthAfrica", Currency.SouthAfricanRand, "za", "zaf"),
    SouthKorea("SouthKorea", Currency.SouthKoreanWon, "kr", "kor"),
    Spain("Spain", Currency.Euro, "es", "esp", isTier1 = true),
    SriLanka("SriLanka", Currency.SriLankanRupee, "lk", "lka"),
    StKittsAndNevis("StKittsAndNevis", Currency.UnitedStatesDollar, "kn", "kna"),
    StLucia("StLucia", Currency.UnitedStatesDollar, "lc", "lca"),
    StVincentAndTheGrenadines("StVincentAndTheGrenadines", Currency.UnitedStatesDollar, "vc", "vct"),
    Suriname("Suriname", Currency.UnitedStatesDollar, "sr", "sur"),
    Sweden("Sweden", Currency.SwedishKrona, "se", "swe", isTier1 = true),
    Switzerland("Switzerland", Currency.SwissFranc, "ch", "che", isTier1 = true),
    Taiwan("Taiwan", Currency.TaiwaneseDollar, "tw", "twn"),
    Tajikistan("Tajikistan", Currency.UnitedStatesDollar, "tj", "tjk"),
    Tanzania("Tanzania", Currency.TanzanianShilling, "tz", "tza"),
    Thailand("Thailand", Currency.ThaiBaht, "th", "tha"),
    Tonga("Tonga", Currency.UnitedStatesDollar, "to", "ton"),
    TrinidadAndTobago("TrinidadAndTobago", Currency.UnitedStatesDollar, "tt", "tto"),
    Tunisia("Tunisia", Currency.UnitedStatesDollar, "tn", "tun"),
    Turkey("Turkey", Currency.TurkishLira, "tr", "tur"),
    Turkmenistan("Turkmenistan", Currency.UnitedStatesDollar, "tm", "tkm"),
    TurksAndCaicosIslands("Turks&Caicos", Currency.UnitedStatesDollar, "tc", "tca"),
    Uganda("Uganda", Currency.UnitedStatesDollar, "ug", "uga"),
    Ukraine("Ukraine", Currency.UkrainianHryvnia, "ua", "ukr"),
    UnitedArabEmirates("UAE", Currency.UnitedArabEmiratesDirham, "ae", "are"),
    UnitedKingdom("UK", Currency.BritishPound, "gb", "gbr", isTier1 = true),
    UnitedStates("USA", Currency.UnitedStatesDollar, "us", "usa", isTier1 = true),
    Uruguay("Uruguay", Currency.UnitedStatesDollar, "uy", "ury"),
    Uzbekistan("Uzbekistan", Currency.UnitedStatesDollar, "uz", "uzb"),
    Vanuatu("Vanuatu", Currency.UnitedStatesDollar, "vu", "vut"),
    VaticanCity("VaticanCity", Currency.Euro, "va", "vat", isTier1 = true),
    Venezuela("Venezuela", Currency.UnitedStatesDollar, "ve", "ven"),
    Vietnam("Vietnam", Currency.VietnameseDong, "vn", "vnm"),
    Yemen("Yemen", Currency.UnitedStatesDollar, "ye", "yem"),
    Zambia("Zambia", Currency.UnitedStatesDollar, "zm", "zmb"),
    Zimbabwe("Zimbabwe", Currency.UnitedStatesDollar, "zw", "zwe"),

    ;

    companion object {
        fun fromIso(iso: Iso): Country? {
            val isoLower = iso.lowercase()
            return when (iso.length) {
                2 -> {
                    entries.find { it.isoAlpha2 == isoLower }
                }
                3 -> {
                    entries.find { it.isoAlpha3 == isoLower }
                }
                else -> {
                    null
                }
            }
        }

        fun fromBillingCurrency(currency: Currency): List<Country>? {
            return entries
                .filter { it.billingCurrency == currency }
                .ifEmpty { null }
        }

        val tier1Countries: List<Country>
            get() = entries.filter { it.isTier1 }
        val nonTier1Countries: List<Country>
            get() = entries.filter { !it.isTier1 }
    }
}